### ISSUE TITLE
[bug] max login error

### ISSUE THREAD

**Issue by signebedi** [signebedi/gita-api#45]
```
[2024-01-25 19:11:18,887] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/opt/gita-api/venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/gita-api/venv/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/gita-api/venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/gita-api/venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/gita-api/app/__init__.py", line 186, in login
    if user.failed_login_attempts >= app.config["MAX_LOGIN_ATTEMPTS"]:
TypeError: '>=' not supported between instances of 'int' and 'function'
```

**Comment by signebedi** [comment]
Maybe:

```python
def default_get_max_login_attempts(default):
    x = os.getenv('MAX_LOGIN_ATTEMPTS', default)
    return False if x == "False" else int(x)
```
